name: Deploy Ansible Configuration Only

on:
  workflow_dispatch:
    inputs:
      web_ip:
        description: 'Public IP of the Web VM (Goa-Web-VM)'
        required: true
        type: string
      app_ip:
        description: 'Public IP of the App VM (Goa-AppDB-VM)'
        required: true
        type: string

jobs:
  configure-servers:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key via Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_PRIVATE_KEY }}

      - name: Create Ansible Inventory
        run: |
          mkdir -p ansible
          cat << EOF > ansible/inventory.ini
          [webserver]
          ${{ github.event.inputs.web_ip }} ansible_user=ubuntu

          [appserver]
          ${{ github.event.inputs.app_ip }} ansible_user=ubuntu
          EOF

      - name: Run Ansible Configuration & Deployment
        working-directory: ./ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: ansible-playbook -i inventory.ini deploy_app.yml
